import os
import json
from PIL import Image
import numpy as np

folder = r'public/images/bucket/213'

BUCKET_METADATA = [
    {
        "num": 1,
        "label": "Korean Silk Ivory & Classic Bow",
        "description": "Buket origami kertas sutra ivory dengan lipatan sayap simetris dan ikatan pita satin anggun",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Silk Ivory",
        "colorHex": "#D4C6B8",
        "collarRatio": 0.50,
        "tag": "Baru: Silk Ivory",
    },
    {
        "num": 2,
        "label": "Origami Pleated Fan & Emerald Bow",
        "description": "Buket lipit kipas origami elegan bernuansa krem natural dengan aksen pita satin hijau zamrud",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Pleated Ivory & Emerald",
        "colorHex": "#C4B298",
        "collarRatio": 0.55,
        "tag": "Baru: Pleated Fan",
    },
    {
        "num": 3,
        "label": "Grand Ivory Layered Royale",
        "description": "Buket mega mewah bersayap kertas tebal bersusun berlapis untuk karangan bunga rimbun berkelas",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Layered Ivory Royale",
        "colorHex": "#A8947F",
        "collarRatio": 0.44,
        "tag": "Baru: Grand Royale",
    },
    {
        "num": 4,
        "label": "Pastel Sky Blue & Powder Pink Bow",
        "description": "Buket modern kerucut biru langit pastel yang lembut dengan pita baby pink manis",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Pastel Sky Blue",
        "colorHex": "#A5B5C1",
        "collarRatio": 0.50,
        "tag": "Baru: Sky Blue",
    },
    {
        "num": 5,
        "label": "Blush Pink Petite Elegance",
        "description": "Buket ramping kertas merah muda pastel dengan juntaian pita sutra senada yang anggun",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "10-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Blush Pink",
        "colorHex": "#C3A29B",
        "collarRatio": 0.52,
        "tag": "Baru: Petite Blush",
    },
    {
        "num": 6,
        "label": "Dusty Rose & Mauve Velvet",
        "description": "Buket origami nuansa dusty rose dan mauve hangat berpadu dengan simpul pita satin romantis",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Dusty Rose",
        "colorHex": "#B87785",
        "collarRatio": 0.52,
        "tag": "Baru: Dusty Rose",
    },
    {
        "num": 7,
        "label": "Pleated Golden Kraft & Forest Ribbon",
        "description": "Buket lipit vertikal warna kraft emas dengan ikatan pita hijau botol yang kontras dan estetik",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Golden Kraft & Forest",
        "colorHex": "#BD9972",
        "collarRatio": 0.52,
        "tag": "Baru: Golden Pleat",
    },
    {
        "num": 8,
        "label": "Ocean Breeze & Slate Cyan Flute",
        "description": "Buket fluted origami warna biru laut slate dengan ikatan pita satin perak kebiruan",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Slate Cyan",
        "colorHex": "#506B78",
        "collarRatio": 0.52,
        "tag": "Baru: Ocean Breeze",
    },
    {
        "num": 9,
        "label": "Scalloped Ruffle Ivory & Pink Satin",
        "description": "Buket renda mekar kelopak bergelombang ivory halus dengan pita satin pink manis",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Ivory Scalloped Ruffle",
        "colorHex": "#DFCFBE",
        "collarRatio": 0.48,
        "tag": "Baru: Scalloped Ivory",
    },
    {
        "num": 10,
        "label": "Pure White Haute Couture & Rose Satin",
        "description": "Buket mega putih bersih berlapis haute couture dengan pita satin mawar merah muda",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Pure White Couture",
        "colorHex": "#CFBCB7",
        "collarRatio": 0.46,
        "tag": "Baru: White Couture",
    },
    {
        "num": 11,
        "label": "Geometric Origami Pyramid Pocket",
        "description": "Buket kantung lipatan geometris origami modern berwarna kraft linen dengan simpul minimalis",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Linen Origami",
        "colorHex": "#AC9E8F",
        "collarRatio": 0.46,
        "tag": "Baru: Origami Pyramid",
    },
    {
        "num": 12,
        "label": "Rustic Kraft Cone & Natural Twine",
        "description": "Buket kerucut kertas kraft cokelat alami dengan lilitan simpul tali rami natural",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Natural Kraft & Twine",
        "colorHex": "#867056",
        "collarRatio": 0.50,
        "tag": "Baru: Kraft Cone",
    },
    {
        "num": 13,
        "label": "Wide Geometric Origami Envelope",
        "description": "Buket origami bersudut tajam modern kertas kraft krem berserat premium",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Geometric Kraft Envelope",
        "colorHex": "#B2A596",
        "collarRatio": 0.46,
        "tag": "Baru: Geometric Kraft",
    },
    {
        "num": 14,
        "label": "Petite Fan Pleat & Jute Knot",
        "description": "Buket mini lipatan kipas kertas kraft kompak dengan simpul rami untuk rangkaian bunga mungil",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "10-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Kraft Fan Pleat",
        "colorHex": "#B3A08B",
        "collarRatio": 0.52,
        "tag": "Baru: Petite Fan",
    },
    {
        "num": 15,
        "label": "Minimalist Kraft Bloom Box",
        "description": "Box persegi kertas kraft kokoh modern untuk display bunga meja yang rapi dan elegan",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "10-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Kraft Bloom Box",
        "colorHex": "#9D8467",
        "collarRatio": 0.38,
        "tag": "Baru: Bloom Box",
    },
    {
        "num": 16,
        "label": "Slim Rustic Wrap & Folded Tails",
        "description": "Buket kerucut ramping kertas kraft cokelat dengan juntaian lipatan kertas artistik",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "10-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Slender Kraft",
        "colorHex": "#6C5A42",
        "collarRatio": 0.52,
        "tag": "Baru: Slim Rustic",
    },
    {
        "num": 17,
        "label": "Classic Brown Kraft Cone & Hemp Bow",
        "description": "Buket kerucut cokelat klasik favorit toko bunga dengan simpul tali goni estetik",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Classic Brown Kraft",
        "colorHex": "#957B61",
        "collarRatio": 0.52,
        "tag": "Baru: Brown Kraft Cone",
    },
    {
        "num": 18,
        "label": "Scalloped Edge Kraft & Twine Flower",
        "description": "Buket tepi bergelombang renda kertas kraft dengan ornamen simpul bunga rami vintage",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Scalloped Edge Kraft",
        "colorHex": "#C1B09C",
        "collarRatio": 0.48,
        "tag": "Baru: Scalloped Kraft",
    },
    {
        "num": 19,
        "label": "Spiral Kraft Cone & Emerald Ribbon",
        "description": "Buket kerucut ulir spiral warna cokelat kraft dengan lilitan pita satin hijau zamrud",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "10-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Spiral Kraft & Emerald",
        "colorHex": "#7C6B53",
        "collarRatio": 0.52,
        "tag": "Baru: Spiral Kraft",
    },
    {
        "num": 20,
        "label": "Wide Open Envelope & Twine Wrap",
        "description": "Buket saku amplop bukaan lebar dengan lining hitam dan ikatan tali rami",
        "category": "koran",
        "themeName": "Vintage Koran",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Kraft Letter Envelope",
        "colorHex": "#6D5849",
        "collarRatio": 0.42,
        "tag": "Baru: Envelope Pouch",
    },
    {
        "num": 21,
        "label": "Radial Pleated Collar & Forest Knot",
        "description": "Buket leher lingkar berlipit radial mewah dengan kerucut kraft dan pita hijau hutan",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Radial Pleated Kraft",
        "colorHex": "#8B7158",
        "collarRatio": 0.52,
        "tag": "Baru: Radial Pleat",
    },
    {
        "num": 22,
        "label": "Petite Asymmetric Kraft Cone",
        "description": "Buket mini kerucut asimetris dengan pita hijau zaitun untuk buket single / mini bloom",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "10-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Petite Asymmetric Kraft",
        "colorHex": "#66523E",
        "collarRatio": 0.50,
        "tag": "Baru: Petite Cone",
    },
    {
        "num": 23,
        "label": "Square Rustic Kraft Tub & Jute Tie",
        "description": "Wadah pot kraft persegi lipat natural dengan aksen tali rami pedesaan",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Square Kraft Tub",
        "colorHex": "#92735A",
        "collarRatio": 0.38,
        "tag": "Baru: Rustic Tub",
    },
    {
        "num": 24,
        "label": "Flared Wings Kraft & Twine Wrap",
        "description": "Buket sayap lebar ganda kertas kraft cokelat dengan ikatan tali rami kencang",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Flared Wings Kraft",
        "colorHex": "#98765E",
        "collarRatio": 0.50,
        "tag": "Baru: Flared Wings",
    },
    {
        "num": 25,
        "label": "Grand Majestic Kraft & Layered Wings",
        "description": "Buket sayap megah kertas kraft cokelat bersusun tinggi untuk rangkaian buket besar",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Grand Majestic Kraft",
        "colorHex": "#A3846B",
        "collarRatio": 0.50,
        "tag": "Baru: Majestic Kraft",
    },
    {
        "num": 26,
        "label": "Petite Fluted Tulip & Satin Emerald",
        "description": "Buket tulip mini kertas kraft halus dengan pita satin hijau botol berkilau",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "10-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Petite Tulip Kraft",
        "colorHex": "#8B745A",
        "collarRatio": 0.50,
        "tag": "Baru: Petite Tulip",
    },
    {
        "num": 27,
        "label": "Layered Rustic Kraft & Triple Twine",
        "description": "Buket lipatan kraft bersusun alami dengan simpul tali goni tebal",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Layered Brown Kraft",
        "colorHex": "#987E64",
        "collarRatio": 0.50,
        "tag": "Baru: Layered Kraft",
    },
    {
        "num": 28,
        "label": "Vintage Newspaper Print Cone",
        "description": "Buket mini kerucut koran vintage tipografi klasik dengan ikatan tali rami antik",
        "category": "koran",
        "themeName": "Vintage Koran",
        "sizeCategory": "10-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Vintage Newspaper",
        "colorHex": "#AC9E8D",
        "collarRatio": 0.48,
        "tag": "Baru: Newsprint Cone",
    },
    {
        "num": 29,
        "label": "Trapezoid Kraft Tote Pouch",
        "description": "Buket pouch trapesium kertas kraft kokoh dengan lilitan tali goni silang",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Trapezoid Kraft",
        "colorHex": "#94775D",
        "collarRatio": 0.38,
        "tag": "Baru: Kraft Tote",
    },
    {
        "num": 30,
        "label": "Origami Letter Envelope Pocket",
        "description": "Buket saku amplop surat origami dengan tutup runcing dan pita hijau lumut",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Letter Envelope Kraft",
        "colorHex": "#B9AB95",
        "collarRatio": 0.44,
        "tag": "Baru: Letter Envelope",
    },
    {
        "num": 31,
        "label": "Layered Scalloped Lace Capelet",
        "description": "Buket kerah renda bersusun renda bergerigi anggun warna kraft lembut",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Scalloped Lace Kraft",
        "colorHex": "#BAADA0",
        "collarRatio": 0.48,
        "tag": "Baru: Scalloped Lace",
    },
    {
        "num": 32,
        "label": "Diamond Origami Fold & Forest Bow",
        "description": "Buket lipatan wajik belah ketupat modern berwarna krem linen dengan pita satin hijau",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Diamond Origami",
        "colorHex": "#A89E87",
        "collarRatio": 0.48,
        "tag": "Baru: Diamond Fold",
    },
    {
        "num": 33,
        "label": "Tulip Petal Kraft & Gathered Base",
        "description": "Buket kelopak tulip melengkung anggun dengan ikatan simpul rami di bagian bawah",
        "category": "rustic",
        "themeName": "Rustic Wood",
        "sizeCategory": "25-flowers",
        "geometryType": "barrel-tub",
        "colorName": "Tulip Petal Kraft",
        "colorHex": "#BDB0A3",
        "collarRatio": 0.48,
        "tag": "Baru: Tulip Petal",
    },
    {
        "num": 34,
        "label": "Haute Couture Snow White Layered",
        "description": "Buket putih salju megah bertumpuk busana couture dengan pita satin blush mawar",
        "category": "korean",
        "themeName": "Korean Classic",
        "sizeCategory": "25-flowers",
        "geometryType": "origami-wrap",
        "colorName": "Snow White Couture",
        "colorHex": "#B3ACA6",
        "collarRatio": 0.46,
        "tag": "Baru: White Couture II",
    },
]

def process_all_buckets():
    print(f"Starting processing of {len(BUCKET_METADATA)} buckets...")
    fade_len = 35

    for item in BUCKET_METADATA:
        num = item["num"]
        src_path = os.path.join(folder, f"{num}.png")
        if not os.path.exists(src_path):
            print(f"Skipping {num}, not found: {src_path}")
            continue

        img = Image.open(src_path).convert("RGBA")
        arr = np.array(img, dtype=np.float32)
        H, W, _ = arr.shape

        collar_y = int(H * item["collarRatio"])

        # 1. Back image (entire image)
        back_path = os.path.join(folder, f"{num}_back.png")
        img.save(back_path)

        # 2. Front image (collar and below, with fade)
        front_arr = arr.copy()
        for y in range(H):
            if y < collar_y:
                front_arr[y, :, 3] = 0
            elif y < collar_y + fade_len:
                factor = (y - collar_y) / float(fade_len)
                front_arr[y, :, 3] *= factor

        front_img = Image.fromarray(np.uint8(front_arr))
        front_path = os.path.join(folder, f"{num}_front.png")
        front_img.save(front_path)

        print(f"[OK] Processed bucket {num}: collarY={collar_y}")

    print("\nAll 34 buckets processed into _back.png and _front.png successfully!")

if __name__ == "__main__":
    process_all_buckets()
